### PR TITLE
allow review of project options

### LINKED ISSUE #462: Show project options on the review project page
In #450 the option was added for new projects.  Show this option on the review projects page.  Allow the user to change this option.

### PR DESCRIPTION
**Pull request by biplovbhandari**
fixes #462

### CODE REVIEW

**Comment by sirmspencer** [comment]
For update_project, follow the same pattern you used in create project, and pass the project_options json.

**Comment by biplovbhandari** [comment]
@sirmspencer please review

**Comment by sirmspencer** [comment]
src/main/resources/public/jsx/review-project.js
Line 258, event is not used
Line 264, 265, 266 missing trailing comma (eslint rule 'comma-dangle')

**Comment by biplovbhandari** [comment]
@sirmspencer Please review

**Comment by sirmspencer** [comment]
src/main/java/org/openforis/ceo/local/JsonProjects.java
Lines 745-747, 1320-1322

src/main/java/org/openforis/ceo/postgres/PostgresProjects.java
515-514, 909-911

You do not need to create a json object just to convert it back to a string.  Use getOrEmptyString().getAsString() == "" for checking for valid data because it checks for more than just an empty value. We could update that function to take an optional fall back string, but lets not do that in this PR.  Your final versions for all four locations should look more like this:
```
final var projectOptions = getOrEmptyString(jsonInputs, "projectOptions").getAsString();
pstmt.setString(6, projectOptions == "" ? "{\"showGEEScript\":false}" : projectOptions);
```

**Pull request merged**
