### PR TITLE
Create / edit project wizard

### PR DESCRIPTION
**Pull request by sirmspencer**

### CODE REVIEW

**Comment by lambdatronic** [comment]
projects.clj:
- Line 54: single-project-list-object is only used here and should thus be inlined.
- Line 78: Session keys (like :userId) are already type-converted.
- Lines 87,116: If you can get the JSON names to match the DB names, you could replace this verbose destructuring/restructuring code with `(map-keys snake-to-camel project)` and then `assoc` any type conversions that are needed.
- Lines 106,129: In response to your TODO, the :sampleValues attribute is a legacy name and should be updated to :surveyQuestions.

custom.css:
- Lines 151,157,160,161,167,171,172,179,182,183,...: Add a space after the colon.
- Lines *: Use lowercase letters for hex colors everywhere.
- Lines *: !important is a code wart used by programmers who can't make their styles cascade cleanly. Jerome used this a lot. Please try to avoid and/or eliminate it wherever possible.

project.sql:
- Lines 762,894: RETURNS TABLE
- Line 780: Missing editable and valid_boundary fields.

**Comment by sirmspencer** [comment]
Lines 87,116: If you can get the JSON names to match the DB names, you could replace this verbose destructuring/restructuring code with (map-keys snake-to-camel project) and then assoc any type conversions that are needed.
Lines 106,129: In response to your TODO, the :sampleValues attribute is a legacy name and should be updated to :surveyQuestions.
-- I have a clean up TODO to conform the variable names.  We can look at (map-keys snake-to-camel project), or adding snake-to-camel to the next.jdbc call.

Line 780: Missing editable and valid_boundary fields. 
-- They are only used in home.js and are still part of the get-project-list definition, so I removed them from get-project-by-id.

**Comment by lambdatronic** [comment]
collection.js:
- Lines 142,157,169: Move `fetch` call to next line to match `getImageryList`.

SurveyCollection.js:
- Line 46: Missing semicolon.

home.js:
- Line 266: Why doesn't userInstitutionList have a value?
- Lines 287-288: Move ? and : onto the beginning of the following lines for consistency with the rest of this file's multi-line ternary operators.

mercator.js:
- Line 1258: Why are we hiding the dragbox layer?

**Comment by sirmspencer** [comment]
Line 266: Why doesn't userInstitutionList have a value?
- Its a boolean. There is a lint rule that is auto correcting it to this short hand notation.  I didnt add it specifically, so I have nothing against changing it. Im not sure which rule it is though.

Line 1258: Why are we hiding the dragbox layer?
- One of the things we talked about was how I change the boundary process a little to accommodate future feature requests.  With the updated flow, I set the boundary from the drag drop interaction (AOIMap, line 82). The updated boundary is automatically then drawn in the currentAOI layer.  It end up working better IMO.  In this implementation you see a blue box while drawing and the yellow aoi when finished.  If you look at collect.earth you will see the yellow wrapping the blue box as you draw.

**Comment by lambdatronic** [comment]
project-admin.js:
- Line 8: No blank line in imports. (I see that you are putting one between NPM imports and imports from our files, which is fine.)
- Line 52: Why not just set privacyLevel in this.blankProject?
- Lines 73-87: Use this debugged and restructured componentDidUpdate() function:
```js
componentDidUpdate(prevProps, prevState) {
    const {plotDistribution, sampleDistribution, institution} = this.state.projectDetails;

    if (plotDistribution !== prevState.projectDetails.plotDistribution) {
        const newSampleDistribution = ["random", "gridded"].includes(plotDistribution) && ["csv", "shp"].includes(sampleDistribution)
              ? "random"
              : plotDistribution === "shp" && ["random", "gridded"].includes(sampleDistribution)
              ? "shp"
              : sampleDistribution;
        if (newSampleDistribution !== sampleDistribution) this.setState({sampleDistribution: newSampleDistribution});
    }

    if (institution !== prevState.projectDetails.institution) {
        this.getInstitutionImagery(institution);
    }
}
```

**Comment by sirmspencer** [comment]
Line 52: Why not just set privacyLevel in this.blankProject?
-- I think I updated blankProject to match the structure that is returned from a template project.  For template project privacyLevel is the one field we dont update.  So my thought here was that if loading a template does not update privacyLevel, than neither should resetting (clearing) the project.  If this is the case it cant be set as part of blankProject.  Im not set on that, if you want me to update it, I can reset the privacyLevel when I reset the project details.

**Comment by lambdatronic** [comment]
AOIMap.js:
- Line 104: Missing semicolon.
- Lines 107-113: I believe you were wrapping JSX returns in parens to clean up the indentation and make opening tags better align with closing tags.

**Comment by lambdatronic** [comment]
projects.clj:
- Line 50: Why did you add :numPlots?

custom.css:
- Lines 70,71,103-105,126-141,171,172,179,283,286,287,368,369,374,387-389,426,427,432,433,458,474,477,480,484-488,494,498,505-511,523-526,530-532,548-560,566,570,571,611,623,661,: Add a space after the colon (and not before it).
- Lines 373-390: Fix indentation.
- Line 498: Add a space after the semicolon.
- Lines 432,548,661: !important is a code wart used by programmers who can't make their styles cascade cleanly. Jerome used this a lot. Please try to avoid and/or eliminate it wherever possible.
- Lines *: There appears to be no consistency between around using a space before the initial { in a style definition nor around placing blank lines before and after style definitions.
- Lines *: Replace headers like this:
```
/* Fonts */
/*************/
```
  with this:
```
/*************/
/* Fonts     */
/*************/
```  

collection.js:
- Lines 152,153,163-166,: Fix indentation.

home.js:
- Line 266: userInstitutionList is a pretty poor name for a boolean attribute. It sounds like it should be an array.

project-admin.js:
- Line 83: Either drop this blank line or add one after `const` since the `const` statement applies to both `if` statements.
- Line 84: Review the order of the test args (as per my original function example) to match the first `if`.

AOIMap.js:
- Lines 110-112: Fix indentation.

**Comment by sirmspencer** [comment]
Line 50: Why did you add :numPlots?
- It should not have been dropped.

**Comment by lambdatronic** [comment]
custom.css:
- Lines 79-81,87-89: Indent `url` expressions under `local` expressions.
- Lines 353,359: Fix indentation.
- Lines 354,360: No blank lines between styles.
- Lines 370-383: Fix indentation.
- Lines 388,583,593: Use Title Case In Block-Level Comments
- Line 479: Add a space after the semicolon.
- Line 625: Remove extra blank line.

**Comment by lambdatronic** [comment]
CreateProjectWizard.js:
- Lines 138,199: Remove extra blank line.
- Line 178: Why do you need to intersect the project imagery with the institution imagery? Shouldn't project imagery always be a subset of institution imagery?
- Line 216: This is only correct for plotShape="square". If plotShape="circle", you can estimate the number of gridded samples as `Math.floor(0.785 * steps * steps)`.
- Line 240: `imageryId <= 0`
- Line 259: Missing period.
- Line 271: Should "Sample Design section" be "Plot Design section"?
- Lines 271,305: limit exceeded -> limit has been exceeded
- Line 291: A sample spacing -> A sample resolution
- Line 298: I don't see the rationale for this requirement on gridded
  samples in a circle. `plotSize/Math.sqrt(2)` is the distance from
  the center of a square of side length `plotSize` to one of its 4
  corners. A circle with diameter `plotSize` can still hold the same
  number of sample points along its midline as a square of side length
  `plotSize` and should thus use the same spacing rules as a square
  plot.
- Lines 298,302: Why use parseInt on line 302 but not on line 298? Also, weren't you using `Number()` in earlier functions?
- Lines 332,351,356,374,384,456: Missing semicolon.
- Line 355: Why do we alert users about errors in the current step
  when navigating forward (nextStep) but not when navigating backward
  (prevStep)?
- Line 382: Add `templatePlots: [],`
- Lines 427,438: `/>` -> `></div>`  (Why are you inserting empty divs here?)
- Line 494: StepHelpComponent is always defined for all steps, so this conditional is unnecessary.
- Lines 413,458: In renderStep and render, this.getSteps() is called
  repeatedly and should be stored in a variable at the top of each
  function like so:
```js
const steps = this.getSteps();
```

**Comment by sirmspencer** [comment]
CreateProjectWizard.js:

Line 178: Why do you need to intersect the project imagery with the institution imagery? Shouldn't project imagery always be a subset of institution imagery?
-- Template projects can come from any institution.

Line 216: This is only correct for plotShape="square". If plotShape="circle", you can estimate the number of gridded samples as Math.floor(0.785 * steps * steps).
-- I dont know that the math will be any more accurate because of the way we center the grid in the middle of the plot. This will under estimate until resolution approaches 0. I prefer to have an over estimate for the purpose of this message. For example when the resolution is just less than plotSize/Math.sqrt(2) there will be exactly 4 samples and this math will greatly under estimate the number samples (3.14 samples).  Hopefully future work to preview samples from the back end can give us a better answer.

Line 291: A sample spacing -> A sample resolution
-- We agreed in MM to update the UI to "spacing".  I have a clean up issue to also update the variable names.

Line 298: I don't see the rationale for this requirement on gridded
samples in a circle. plotSize/Math.sqrt(2) is the distance from
the center of a square of side length plotSize to one of its 4
corners. A circle with diameter plotSize can still hold the same
number of sample points along its midline as a square of side length
plotSize and should thus use the same spacing rules as a square
plot.
-- The way we draw gridded samples will put 4 samples in the corner of the square if the resolution is close to the plot size.  For a circle, there is no corners, and those 4 samples get cut off leaving an empty plot.

Lines 298,302: Why use parseInt on line 302 but not on line 298? Also, weren't you using Number() in earlier functions?
-- Biplov wrote the functions with Number().  In JS you dont need to type convert for math. Im taking out the Number() as well.

Line 355: Why do we alert users about errors in the current step
when navigating forward (nextStep) but not when navigating backward
(prevStep)?
-- This is intential.  The user isnt finishing a step necesarily if they are going back.  I also dont check when the user clicks on a specific step.

Lines 427,438: /> -> ></div> (Why are you inserting empty divs here?)
-- A self closing div is OK in JSX. There is no content, its just a spacer and filled circle.

**Comment by lambdatronic** [comment]
Overview.js:
- Lines 21,30: `htmlFor` should refer to an `id` attribute on a form field.
- Line 50: Why is the privacy-public label the only one with a title field?
- Lines 73,85: Move `checked` attribute before `onChange` for consistency with other radio inputs.
- Line 94: Add a space before "to".
- Line 103: Move `className` attribute before `type` for consistency with other checkbox inputs.
- Line 110: Capitalize "Link".
- Line 165: What is the purpose of this unstyled `div`?
- Line 166: Remove space before closing ".
- Line 221: `htmlFor` should refer to an `id` attribute on a form field (and is unnecessary here).
- Line 266: Destructure `context` here to avoid repeated `context.*` references throughout function body.
- Line 275: Capitalize "Link".
- Lines 293-295: Wrap JSX with parens for stylistic consistency.

**Comment by lambdatronic** [comment]
ImagerySelection.js:
- Line 6: Remove blank line.
- Lines 7,19,20: Consider renaming `imageryId` to `defaultImageryId` for clarity.
- Line 7: Move renderImageryRow out of ImagerySelection into a
  standalone function. Otherwise, it will be redefined every time
  ImagerySelection is re-rendered.
- Line 29: No React Fragment is necessary here since both conditional
  branches return a single JSX element. This also means you can remove
  the parens wrapping this function body.
- Lines 34,49,59,76: `htmlFor` should refer to an `id` attribute on a form field (and is unnecessary here).
- Line 41: Don't filter out "Planet Daily" imagery sources. Instead,
  these should be shown with the same tiled "image not available"
  message as SecureWatch imagery.
- Line 58: Don't use `<br>` for spacing between components. Use margin or padding.
- Line 88: Move findImageryName out of ImageryReview into a standalone
  function. Otherwise, it will be redefined every time ImageryReview
  is re-rendered.
- Line 96: What is the purpose of this unstyled div?

**Comment by sirmspencer** [comment]
ImagerySelection.js:

Lines 7,19,20: Consider renaming imageryId to defaultImageryId for clarity.
-- I want to do this through out.  We changed it from base_map_source to imagery_rid right before adding the funcionality to have muiltiple imagery selected. default_imagery_rid would be much more clear, we just didnt get it into that PR.

Line 29: No React Fragment is necessary here since both conditional
branches return a single JSX element. This also means you can remove
the parens wrapping this function body.
-- Interesting my linter was requiring the fragment until I removed the parens and {.

Line 41: Don't filter out "Planet Daily" imagery sources. Instead,
these should be shown with the same tiled "image not available"
message as SecureWatch imagery.
-- There is an issue for this.  It is not part of the scope of this PR.

**Comment by lambdatronic** [comment]
PlotDesign.js:
- Line 15: boundaryMode is a constant. Do we really need to keep this variable?
- Line 29: Use arrow syntax for non-lifecycle methods.
- Line 55: No {} necessary around single-expression function bodies.
- Lines 58,75,116,181,222: Missing semicolon.
- Line 82: What is the purpose of this unstyled div?
- Line 169: defaultValue -> value
- Line 198: No {} necessary around single-expression function bodies.
- Line 209:
```js
File: <span className="font-italic">{this.context.plotFileName || None}</span>
```
- Lines 249,254: `showAOI: false` (for consistency and clarity)
- Line 277: Remove - at end of line.
- Line 281: Add a space before `=>`.
- Line 306: `\n` doesn't have any effect in HTML strings.
- Line 340: "Spatial distribution" (Use sentence case to match the other plot attributes)
- Lines 329,385: Do PlotReview and AOIReview need to be exported?

**Comment by sirmspencer** [comment]
PlotDesign.js:

Line 82: What is the purpose of this unstyled div?
--It groups the two radio inputs

Lines 329,385: Do PlotReview and AOIReview need to be exported?
-- They are used in ReviewForm.js as well.

**Comment by lambdatronic** [comment]
SampleDesign.js:
- Line 26: Missing semicolon.
- Line 43: No {} around single expression function bodies.
- Line 54: Use this instead:
```js
File: <span className="font-italic">{this.context.sampleFileName || "None"}</span>
```
- Line 77: How do we support sampleDistribution="center" when plotDistribution="shp"? I wasn't aware that we could do this.
- Line 79: on the center -> in the center
- Line 110: this.context.setProjectState -> setProjectState
- Line 120: Remove - at end of line.
- Line 141: Add a space before `=>`
- Lines 160,165,166: `\n` does not have any effect in HTML strings.
- Line 199: /plot -> / plot (or "per plot")
- Line 223: its -> it's
- Line 224: Don't define local functions within a React function
  component because the functions are redefined every time the
  component is re-rendered. Since the actual return expression is so
  short, it makes more sense to inline this code using a chain of
  ternary operators like so:
```js
export function SamplePreview() {
    // TODO: Update messaging so it's more clear when shp is defined at the plot level, especially with CSV samples
    return (
        <ProjectContext.Consumer>
            {({plotDistribution, sampleDistribution, plotShape}) =>
                <div className="p-3">
                    {(plotDistribution === "shp")
                     ? <h3>The system cannot currently generate a preview of plot shp files.</h3>
                     : (sampleDistribution === "csv")
                     ? <h3>The system cannot currently generate a preview of sample csv files.</h3>
                     : (sampleDistribution === "shp")
                     ? <h3>The system cannot currently generate a preview of sample shp files.</h3>
                     : (
                         <div>
                             <h3>The following is a mock up of a {plotShape} plot with {sampleDistribution} samples.</h3>
                             <img
                                 className="w-100 h-100"
                                 src={"/img/examples/" + plotShape + "-" + sampleDistribution + ".webp"}
                             />
                         </div>
                     )}
                </div>
            }
        </ProjectContext.Consumer>
    );
}
```
- Line 226: shape -> plot shp (I already made this change in the example code above.)

**Comment by sirmspencer** [comment]
Line 77: How do we support sampleDistribution="center" when plotDistribution="shp"? I wasn't aware that we could do this.
-- See projects.clj line 450

**Comment by lambdatronic** [comment]
ManageProject.js:
- Line 9: Remove blank line.
- Line 20: Add space after `=>`
- Line 23: Missing semicolon.
- Line 41: Use backquoted string for consistency.
- Line 52: retrieving plot list -> retrieving the plot list
- Lines 97-101: this.stateTransitions is unused.
- Lines 177,183,191: Drop empty className attribute.
- Line 188: Remove extra space after "Unknown".
- Line 240: Didn't we assign a name to the Collection page tab to avoid collisions with the GeoDash?

**Comment by lambdatronic** [comment]
ReviewChanges.js:
- Line 104: Move `);` to next line for consistency with `createProject` or vice versa.

**Comment by lambdatronic** [comment]
SurveyQuestions.js:
- Line 9: Move componentTypes into NewQuestionDesigner's constructor
  as this.componentTypes for consistency with your other project
  component files.
- Lines 29-35: Convert if/else to ?:
- Line 32: No parens around single expression function body.
- Lines 40,43,50,58,60,63: Remove unnecessary blank lines.
- Lines 68-72: Use arrow syntax for non-lifecycle methods and fix indentation:
```js
maxAnswers = (componentType, dataType) =>
    (componentType || "").toLowerCase() === "input"
    ? 1
    : (dataType || "").toLowerCase() === "boolean"
    ? 2
    : 1000;
```
- Line 97: No spaces are `=`.
- Lines 116-126: No arrow syntax for React lifecycle methods.
- Line 148: Destructure setProjectState from this.props on line 130.
- Line 135: "Warning: This is a duplicate question. It will be added as "
- Line 161: "/// Render Functions" (with no trailing slashes for consistency with your other project component files)
- Line 156: event -> ruleId
- Line 157: event.target.id -> ruleId
- Line 167: this.deleteSurveyRule(e.target.id)
- Lines 156-176: deleteSurveyRule and removeButton are not used in this file.
- Line 180: No need for React Fragment. This is just a single table.
- Lines 185,189: value-componenttype -> value-component-type
- Line 257: Move `<label>` tag onto its own line for consistency with the other rows in this table.
- Line 290: Remove unnecessary blank line.
- Lines 292,311: Use lowercase letters in hex colors.
- Lines 307,310: Destructure surveyQuestions and setProjectState from this.props on line 298.
- Line 309: Remove unnecessary blank line.
- Line 318: Wrap JSX in parens for consistent indentation.
- Line 350: Add `answered: []` to `selectedQuestion`.
- Lines 372-375: Use this form to match getChildQuestionIds above (and to label the correct argument as the accumulator):
```js
return childQuestions.reduce((acc, cur) => (
    [...acc, ...this.getChildQuestions(cur.id)]
), [question]);
```
- Line 372: No parens around single expression function body.
- Lines 383,387,392,398: It doesn't look like parentQuestion  or parentAnswer can ever be -1 in this function.

**Comment by sirmspencer** [comment]
Lines 383,387,392,398: It doesn't look like parentQuestion or parentAnswer can ever be -1 in this function.
- They can. parentQuestion === parentAnswer === -1 is true for every top level question

**Comment by lambdatronic** [comment]
SurveyRules.js:
- Line 10: Why did you change selectedRuleType from "none" to "text-match"?
- Lines 28-31: Add a space after the colon.
- Line 55: updateOptions should be refactored into several smaller functions.
- Line 117: addSurveyRule should be refactored into several smaller functions.
- Line 285,332,391,442,501,: No need for React Fragment. This is just a single table row.
- Lines 299,346: Why did you remove the "-select-" option from the "Survey Question:" dropdowns?
- Line 562: Why did you remove the "None" option from the "Answer 2" dropdown?
- Line 579: Convert this function component back to a class component to avoid redefining deleteSurveyRule and removeButton every time the component is re-rendered.

**Comment by sirmspencer** [comment]
Line 10: Why did you change selectedRuleType from "none" to "text-match"?
-- There is no reason so show a dropdown option "none"

Lines 299,346: Why did you remove the "-select-" option from the "Survey Question:" dropdowns?
-- I dont show the dropdown if there is no valid questions.  There is no reason to show a default option

Line 562: Why did you remove the "None" option from the "Answer 2" dropdown?
-- I dont show the dropdown if there is not 2 valid questions.  There is no reason to show a default option

**Comment by lambdatronic** [comment]
Overview.js:
- Lines 188-189: Fix indentation.

ImagerySelection.js:
- Lines 16-17: Fix indentation.

PlotDesign.js:
- Line 279: Remove - at end of line.

SampleDesign.js:
- Line 77: Add a `disabled` attribute to prevent using sampleDistribution="center" when plotDistribution="shp".
- Line 120: Remove - at end of line.
- Lines 156-161: Use clearer formatting:
```js
{totalPlots > 0 && samplesPerPlot > 0
 ? `There will be around ${formatNumberWithCommas(totalPlots * samplesPerPlot)} total samples in the project.`
 : sampleDistribution === "none"
 ? "No samples will be added to the plot."
 : ""
}
```

ManageProject.js:
- Line 239: Didn't we assign a name to the Collection page tab to avoid collisions with the GeoDash?

SurveyQuestions.js:
- Line 12: Wrong location. Please move `this.componentTypes` into NewQuestionDesigner's constructor.
- Line 123: this -> This

SurveyRules.js:
- Line 55: updateOptions should be refactored into several smaller functions.
- Line 117: addSurveyRule should be refactored into several smaller functions.
- Lines 553: Define `constructor(props)`.
- Line 554: event -> ruleId
- Line 555: parseInt(event.target.id) -> ruleId
- Lines 560-573: Simplify `removeButton` like so:
```js
removeButton = (ruleId) => (
    <button
        type="button"
        className="btn btn-outline-red py-0 px-2 mr-1 font-weight-bold"
        onClick={() => this.deleteSurveyRule(ruleId)}
    >
    X
    </button>
);
```
- Lines 583-651: Fix indentation.

**Comment by sirmspencer** [comment]
SampleDesign.js:

Line 77: Add a disabled attribute to prevent using sampleDistribution="center" when plotDistribution="shp".
-- Center is an acceptabe selection for shp, see projects.clj line 450

ManageProject.js:

Line 239: Didn't we assign a name to the Collection page tab to avoid collisions with the GeoDash?
-- Looks like I missed posting a comment, this is done on mount, see collection.js line 52

SurveyRules.js:

Line 55: updateOptions should be refactored into several smaller functions.
Line 117: addSurveyRule should be refactored into several smaller functions.
-- I added an issue for this (785), it is not in the scope of this PR.

Lines 553: Define constructor(props).
-- The constructor is not needed if you are not defining anything on `this`.

**Comment by lambdatronic** [comment]
SurveyRules.js:
- Line 553: Remove unnecessary blank line.
- Line 555: No parseInt needed.

**Pull request merged**
