### PR TITLE
survey answer text validation

### PR DESCRIPTION
**Pull request by rfontanarosa**
This solves #444

### CODE REVIEW

**Comment by sirmspencer** [comment]
- 494, since you are checking as they type, do not throw and alert.  Repeat alerts are quite annoying.

**Comment by rfontanarosa** [comment]
it's time to think about form validation. :)

**Comment by sirmspencer** [comment]
> it's time to think about form validation. :)

Sure, and you can easily move your regex check to when the user clicks save, instead of as they type.

**Comment by sirmspencer** [comment]
We may need to update your regex, it does not allow negatives or decimals.  I think the easiest solution is to just change the input type to "number" on line 517, then you dont need any regex validation.

**Pull request merged**
