### PR TITLE
added sanitizing logic, added a validation url for GeoServer imagery …

### LINKED ISSUE #682: Check for ? and & in WMS url
These are invalid characters for a WMS (geoserver) url, the query params are supposed to be in the json params input box for a new imagery.  
- [x] If there is just a ? at the end, remove it.  
- [x] If there is stuff after the ? then warn the user to update their imagery.

### PR DESCRIPTION
**Pull request by rfontanarosa**
fix #682

the idea is to have a generic sanitizing logic that could be applied automatically at submit time.

the validation logic is already implemented, I've just added a GeoServer condition.

### CODE REVIEW

**Comment by sirmspencer** [comment]
src/js/imagery/imageryOptions.js
11 You wont need more than one sanitizer. The function can do as many checks as it needs to. Change this to `sanitizer:` and dont use an array
557 Instead of creating a new variable, just update 
656 move this above uploadCustomImagery so it is defined before it is called.
657 In this context you should be using forEach.  every is a function that returns true and false.
659 You are mutating sourceConfig.  Create a copy before hand to make this function immutable over all. Use `const sourceConfigCopy = {...sourceConfig};`
666 This is fine for now. In a separate PR, we should move all of these validations into the imageryOptions definition like you did with the sanitizer.

**Comment by sirmspencer** [comment]
src/js/imagery/imageryOptions.js
11 This can be simplified. `url => url.endsWith("?") ? url.slice(0, -1) : url` url should never be null, are you finding otherwise?
558 Dont use a ternary because you are not returning anything.  Use if statements for side affects.
```
if (o.sanitizer) {
    sourceConfigCopy[o.key] = o.sanitizer(sourceConfigCopy[o.key])
}
```
667 I prefer a period over !. The app does not need to be yelling at the user. "The field \"WMS Url\" should not contain the query string. Please put those values in the field \"Additional WMS Params (as JSON object) \""

**Comment by rfontanarosa** [comment]
fix #955

**Comment by sirmspencer** [comment]
src/js/imagery/imageryOptions.js
11 You have a unecessary slice `url => url.endsWith("?") ? url.slice(0, -1) : url`
19 can you take this out and make another PR.  Ive been checking the logic more thouroghly and it looks like it needs some work.  I am getting empty {} for most inputs.

**Pull request closed without merging**
