### PR TITLE
Add mailing list functionality (2)

### LINKED ISSUE #386: Add mailing list functionality
Add a new page that is only accessible to admin@openforis.org.

On this page, there should be two form fields (Subject and Body) as
well as a button labeled "Send to All CEO Users".

Pushing this button should send a mass email to all registered users
(i.e., everyone with an email address in the `users` table).

### PR DESCRIPTION
**Pull request by rfontanarosa**
Fixes #386

The page /mailing-list is accessible only by the user who has its id equals to 1.

I've used the same style of the Account page and I've added CKEditor as framework to create a WYSWYG editor.

I've improved the Mail class, is now possible sending mail in text/plain and text/html format to a list of recipients, a list of cc recipients and a list of bcc recipients.

### CODE REVIEW

**Comment by sirmspencer** [comment]
general comments
- The user needs to be able to unsubscribe without being logged in.  You will need to create another page for unsubscribe and link to it in the email.  Please use react, not freemarker.
- We prefer API routes for all non page relited routing instead the form submission routes.  The pages that still use form submissions are mostly old html template files.  They have not been updated because they are low priority.
- The account page has not gotten the full React and route conversion like the other pages.  It is not a good example.  Feel free to convert the form submition on the account page to a proper API route after this PR.

src/main/java/org/openforis/ceo/Server.java
Line 102, you are missing authentication for POST.
Line 201, create an API route instead of a form submit.
Lines 307-312 align = with line 313

src/main/java/org/openforis/ceo/db_api/Users.java
Line 23, sendMailingList -> submitEmailForMailingList

src/main/java/org/openforis/ceo/local/JsonUsers.java
Line 33-42 align equals with 43
Line 183, 334 "mailing-list" -> "on-mailing-list"
Line 522, 534 sendMail has been updated, fix parameters
Line 574 sendMailingList -> submitEmailForMailingList
Line 579, 588, 591 After this is an API, this wont work.  Throw a runtime exception and catch it on the front end. See checkPlotLimits in ProjectUtils.java and createProjectApi in create-project.
Line 587, sendMailingList is static, `Mail.sendMailingList` -> `sendToMailingList`
Line 594 return "";

PostgresUsers.java:
Line 23, remove non static import.
Line 29-33 align equals with 34
Line 133, revert this back to use the query param.
Line 179, you dont need a variable here. `pstmt_mailing_list.setBoolean(2, mailingListSubscription != null);`
Line 435, 443, sendMail has been updated, fix parameters
Line 476 sendMailingList -> submitEmailForMailingList
Line 482, 493, 497 After this is an API, this wont work.  Throw a runtime exception and catch it on the front end. See checkPlotLimits in ProjectUtils.java and createProjectApi in create-project.
Line 492, sendMailingList is static, `Mail.sendMailingList` -> `sendToMailingList`
Line 500 return "";

src/main/java/org/openforis/ceo/utils/Mail.java
Lines 19-21, I think constants here are uneccesary
Lines 96-102, this will break if the user sends an invalid type. Use `message.setContent(body, contentType != null %%  contentType.equals("text/html") ? "text/html" : "text/plain");`
Line 114 sendMailingList -> sendToMailingList
Line 114 this line is too long
Line 115 use var, this object is mutated in your code.
Line 115 add link to unsubscribe here
Lines 117 - 123, you dont need an intermediary variable here. `import java.util.Collection;` is no longer needed.
```
bcc.stream()
    .collect(Collectors.groupingBy(it -> counter.getAndIncrement() / chunkSize))
    .values()
    .forEach(chunkBcc -> {
        sendMail(from, null, null, chunkBcc, smtpServer, smtpPort, smtpPassword, subject, body, contentType);
});
```

src/main/resources/public/jsx/mailing-list.js
Line 11, add the unsubscribe on the server side the the user cant leave it off
Line 15, 63 submit is a reserved word in html, use submitEmail
Line 18, create a sparate API route for submitting an email
Line 26, The linter does not require a semi colon for the end of a function.  However Gary wants us to use a semi colon if if is a annonomous function.
Lines 28-38
```
onChangeSubject = (event) => this.setState({ subject: event.target.value });

onChangeBody = (event, editor) => this.setState({ body: editor.getData() });
```
Line 53, 63, this line is too long
Line 52, 56, you dont really need `for` here.  If you want to keep it, you need to use `forHtml`
Lines 77-79, this will fit on one line

src/main/resources/sql/load_ceo_functions.sql
Line 312, use the same name in the parameter as the columns. `set_on_mailing_list(_user_uid integer, _on_mailing_list boolean)`
Line 315, 324, 333 on_mailing_list

src/main/resources/sql/load_ceo_tables.sql
Line 12 on_mailing_list

src/main/resources/sql/update_2020-05-28.sql
Update file based on the above comments.

src/main/resources/public/js/ckeditor.js
remove unused file

src/main/resources/public/jsx/account.js
Line 99, this is uneeded if you use ES6 annonomous functions
Line 107, convert this to an annonomous function definition
Line 118 - 123, `toggleMailingListSubsciprion = () => this.setState({ mailingListSubscription: !this.state.mailingListSubscription });`

**Comment by rfontanarosa** [comment]
> * The user needs to be able to unsubscribe without being logged in.  You will need to create another page for unsubscribe and link to it in the email.

Ok, but how. The main issue is that we can't personalize the emails because with gmail we have a daily quota, so we can't put an email or a token inside the query string of the unsubscribe link. The only thing that we can do is link a page in which the user can submit his email address but it should do it manually.

**Comment by sirmspencer** [comment]
> Ok, but how. The main issue is that we can't personalize the emails because with gmail we have a daily quota, so we can't put an email or a token inside the query string of the unsubscribe link. The only thing that we can do is link a page in which the user can submit his email address but it should do it manually.

Yes, create a page where a user can type their email into a box and click unsubscribe.

**Comment by sirmspencer** [comment]
Please send an email to the user after they unsubsribe that lets them know they were unsubscribed, and provides a link to the user account page if they wish to re-register

src/main/java/org/openforis/ceo/Server.java
- 101-104 This section is for HTML requests. "/mailing-list" is ok here, "/send-mailing-list" is an API route.  In the section below we send a forbidden responce instead of redirecting.  Move "/send-mailing-list" to the API section.

PostgresUsers.java:

- 74, var onMailingList =       req.queryParams("on-mailing-list");
- 95, mailingListSubscription -> onMailingList
- 138 You need to check if the attribute exists like in Server.java, line 77 / Views.java line 82, etc.  This is done in a few places, create a funtion getSessionUserId() to consilidate this reapeat code.
- 143 final var onMailingList =       req.queryParams("on-mailing-list")
- 185 mailingListSubscription -> onMailingList
- 326 If you use getSessionUserId(), you wont need route security.
- 334 userJson.addProperty("onMailingList", rs.getBoolean("on_mailing_list"));
- 439, 445, Why are you using `Collections.singleton(email)` instead of `Arrays.asList(inputEmail)`
- 494, move var emails = new ArrayList<String>(); into the try block below to limit the scope.
- 513, you can put as many prepared statements as you want in the inital try block.  This should limit your need for as many nested trys.  You also missed a try around the result set.
```
public String unsubscribeFromMailingList(Request req, Response res) {
    var jsonInputs = parseJson(req.body()).getAsJsonObject();
    var inputEmail = jsonInputs.get("email").getAsString();

    try (var conn = connect();
         var pstmt_user = conn.prepareStatement("SELECT * FROM get_user(?)");
         var pstmt_mailing_list = conn.prepareStatement("SELECT * FROM set_mailing_list(?,?)")) {

        pstmt_user.setString(1, inputEmail);
        try (var rs_user = pstmt_user.executeQuery()) {
	        if (rs_user.next()) {
	            pstmt_mailing_list.setInt(1, rs_user.getInt("user_id"));
	            pstmt_mailing_list.setBoolean(2, false);
	            pstmt_mailing_list.execute();
	        }
        }
    } catch (Exception e) {
        System.out.println(e.getMessage());
        throw new RuntimeException(e);
    }
    return "";
}
```

****Line 482, 493, 497 After this is an API, this wont work. Throw a runtime exception and catch it on the front end. See checkPlotLimits in ProjectUtils.java and createProjectApi in create-project.


src/main/java/org/openforis/ceo/utils/Mail.java
Line 114 use var, this is an object that is mutated in your code.

src/main/resources/public/jsx/account.js
- 97 mailingListSubscription -> onMailingList
- 99 Remove extra return
- 107 you dont need to pass userId when you use getSessionUserId() in PostgresUsers.java
- 109 `.then(details => this.setState({ onMailingList: details.onMailingList }))`
- 113 `toggleOnMailList = () => this.setState({ onMailList: !this.state.onMailList });`

src/main/resources/public/jsx/mailing-list.js
- 9 you dont need to define default body now that is is only ""
- 12, 28 body: ""
- 26 you dont use response.text so you dont need another .then.
```
.then(response => {
	if (response.ok) {
		this.setState({ subject: "", body: this.defaultBody });
	    alert("Your message has been sent to the mailing list.\n\n");
	} else {
		Promise.reject(response))
	};
})
```
- 37 Handle the event where it occurs. `onChange={e => this.onChangeSubject(event.target.value)}`
- 39 You are not using the event parameter.
- 89 remove extra blank line
- Do not use documentRoot

src/main/resources/public/jsx/unsubscribe-mailing-list.js
- 12 Handle event where occurs `onChangeEmail = (newEmail) => this.setState({ email: newEmail });`
- 25-29 same as above, you dont use response.text so you dont need another .then.
- 41 remove the form action, or update this to match how you just did the login page FTL conversion.
- 73 dont use documentRoot

src/main/resources/sql/load_ceo_functions.sql
- 321 on_mailing_list

src/main/resources/sql/update_2020-05-28_mailing_list.sql
- 1 ALTER TABLE users ADD COLUMN on_mailing_list boolean DEFAULT NULL;
- 12 on_mailing_list

src/main/resources/template/freemarker/mailing-list.ftl
src/main/resources/template/freemarker/unsubscribe-mailing-list.ftl
- 2 use the react navbar instead of the ftl navbar
- 5 do not add a class here, with the react navbar, this no loger wraps mailing-list.  If you need those classes, add them in mailing-list.js
- 14 update to pass the params that the react navbar needs, and dont use document root.

src/main/resources/template/freemarker/navbar.ftl
- Update the new react navbar to match.

**Comment by rfontanarosa** [comment]
Phew, I've followed almost all your instructions, except:

- **39 You are not using the event parameter.** Unfortunately CKeditor 5 requires a function with two parameters: https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change:data

**Comment by sirmspencer** [comment]
> Phew, I've followed almost all your instructions, except:
> 
> * **39 You are not using the event parameter.** Unfortunately CKeditor 5 requires a function with two parameters: https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change:data

That makes sense.  Can you add a comment so no one in the future tries to remove it?

**Comment by sirmspencer** [comment]
PostgresUsers.java:
325 Use getSessionUserId()
529 "You have been unsubscribed from our mailing list and will no longer receive a newsletter.\n\n"
"You can resubscribe to our newsletter by going to your account page.\n\n"

src/main/resources/public/jsx/account.js
107 `fetch("/get-user-details")` This section is only shown when the user is looking at their own page. You dont need to pass userId, use getSessionUserId() in PostgresUsers.java
113 This is not acutally needed because you do not pass them to a child component.
167 `onChange={() => this.setState({ onMailingList: !this.state.onMailingList })}`

src/main/resources/public/jsx/mailing-list.js
- 40 / 42, these are not acutally needed because you do not pass them to a child component.
- 65 `onChange={e => this.setState({ subject: e.target.value })}`
- 72 `onChange={(e, editor) => this.setState({ body: editor.getData() });}`

src/main/resources/public/jsx/unsubscribe-mailing-list.js
- 13 / 59 same as above

src/main/java/org/openforis/ceo/Server.java
- 40, 79 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/local/JsonInstitutions.java
- 21,41 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/local/JsonProjects.java
- 65, 73, 139 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/postgres/PostgresImagery.java
- 12, 66, 86 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/postgres/PostgresInstitutions.java
- 15, 42 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/postgres/PostgresProjects.java
- 48, 56, 163 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/local/JsonUsers.java
- 34, 146 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/postgres/PostgresUsers.java
- 24, 136 use static import `import static org.openforis.ceo.utils.SessionUtils,getSessionUserId;` and move to the static import section

src/main/java/org/openforis/ceo/utils/SessionUtils.java
- 7 Is userId ever used as a string, or should this return and integer?

src/main/resources/public/jsx/unsubscribe-mailing-list.js
- 27 "You have been unsubscribed from mailing list."
- 33 "There was an issue unsubscribing from mailing list."

src/main/java/org/openforis/ceo/Views.java
- 82 req.queryParams("userId") != null ? req.queryParams("userId") : getSessionUserId(req);

**Comment by lambdatronic** [comment]
PostgresUsers.java:
- Line 167: This early return will skip the password and mailing list
  setting code below if the email is updated. In order to support
  multiple simultaneous operations, drop this `return "";` line and
  allow the code to return successfully on line 181.
- Line 530: "CEO Mailing List: Unsubscribe Successful from CEO mailing list!" -> "Successfully unsubscribed from CEO mailing list"
- Line 537: "a unknown" -> "an unknown"

Mail.java:
- Line 19: No blank lines in import block.

account.js:
- Line 188: Unnecessary `name` field.

mailing-list.js:
- Line 22: `subject: subject,`
- Line 23: `body: body,`
- Lines 41,80: Remove `<section></section>` tags. These are already included from start-content.ftl and end-content.ftl in mailing-list.ftl.

unsubscribe-mailing-list.js:
- Line 19: `email: email,`
- Line 51: Unnecessary `name` field.

update_2020-05-28_mailing_list.sql:
- Line 28: `DROP FUNCTION add_user(text, text);`

**Pull request merged**
