### PR TITLE
CEO-455 Use global color vars for the CSS

### PR DESCRIPTION
**Pull request by sifbiri**
## Purpose
Create global color vars instead of using hex values everywhere
## Submission Checklist
- [x] Included Jira issue in the PR title (e.g. `CEO-### <title>`)
- [x] Code passes linter rules (`npm run eslint`/`clj-kondo --lint src`)

### CODE REVIEW

**Comment by sirmspencer** [comment]
Great start!  There are other places in the rest of the code that reference the hex.  Can you update these as well?

**Comment by sirmspencer** [comment]
src/css/custom.css
I had "hide white space changes" set in my last review.  I see now that you changes the indent from 4 to 2. We can talk about doing that at a later point, but it should not be a part of this PR.

src/js/project/CreateProjectWizard.js
469, I was expecting a change here from PR 1532.  It looks like your a few commits behind (I think you based off of 1533).  You can pull the latest development and rebase to see the changes from 1532.

**Comment by sirmspencer** [comment]
src/js/project/CreateProjectWizard.js
475, should the yellow be --yellow?
475, Lets define a var for gray so we can modify it in the future if we need to.  Its also possible the default gray is different for each computer if we dont define it specifically.
475, I think it would be cleaner to set stepColor to the color only and combine with var where used.  `const stepColor = isSelected ? "--lightgreen" : stepComplete ? "--yellow" : "--gray";` or just reduce some redundant code: `const stepColor = 'var(${isSelected ? "--lightgreen" : stepComplete ? "--yellow" : "--gray"})';` (note that I cant type back ticks into github the single quote should be a back tick)

**Comment by sifbiri** [comment]
I don't 

src/js/project/CreateProjectWizard.js
475, Yeah...I corrected it before but somehow slipped with cherry-picking commits and all.
475, Yes, I was debating that in my head. Makes sense. 
475, What if we add a small utility function that decorates the color string to a css var that we can also use elsewhere?

**Comment by sirmspencer** [comment]
This is a little simpler version of my comment above 'var(--${isSelected ? "lightgreen" : stepComplete ? "yellow" : "gray"})';`

**Pull request merged**
