### PR TITLE
CEO-202 Add 'Natural' navigation mode

### PR DESCRIPTION
**Pull request by rjsheperd**
## Purpose

Adds 'Natural' navigation mode to collection UI.

## Related Issues
Closes CEO-202

## Submission Checklist
- [x] Commits include the JIRA issue and the `#review` hashtag (e.g. `CEO-### #review <comment>`)
- [x] Code passes linter rules (`npm run eslint`/`clj-kondo --lint src`)

## Testing

1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing an unanalyzed plot, And I click to the previous plot, Then I am shown my previously analyzed plot.
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing my first analyzed plot, And I click to the previous plot, Then I am shown the last unanalyzed plot.
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing my last unanalyzed plot, And I click to the next plot, Then I am shown the first analyzed plot.
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing my last analyzed plot, And I click to the next plot, Then I am shown the first unanalyzed plot.

## Screenshots

Screen Shot 2021-09-20 at 11 48 19 AM

### CODE REVIEW

**Comment by rjsheperd** [comment]
src/clj/collect_earth_online/db/plots.clj 
_80-84, This is a bit more complex than I was expecting. What edge cases are you coding for?_

The main use cases are:
1. When a user is on a analyzed plot and hits "next", go to the first unanalyzed plot
2. When a user is on a unanalyzed plot and hits "previous", go to the last analyzed plot

Do we want to keep those use cases?

**Comment by sirmspencer** [comment]
src/clj/collect_earth_online/db/plots.clj
77, You dont need admin-mode?, this cant be used in admin mode
78/79, Both of these SQL calls return vectors already sorted by visible_id.
79, You shouldnt need group by since this cant be used in admin mode.
81, This seems like its only working because you are resorting (first analyzed) to the beginning of the list on 106.  next gets the first to wrap around to the beginning of list so use `(concat (first analyzed) unanalyzed)` and dont sort.
82, `(conj analyzed (last unanalyzed))`
83, `(concat analyzed unanalyzed)`
106, You shouldnt need to sort here.

81-83 WRT the use cases.  
```
The main use cases are:

When a user is on a analyzed plot and hits "next", go to the first unanalyzed plot
When a user is on a unanalyzed plot and hits "previous", go to the last analyzed plot
Do we want to keep those use cases?
```
Good question.  What feels more "natural"? With:
`A1 - A2 - A3 - A4 - U5* - U6 - U7`

1. the user hits back 4 times
`A1* - A2 - A3 - A4 - U5* - U6 - U7`
2. The user hits next.  What feels natural:
   a. next goes to A2, which they just saw
   b. skips ahead to U5 to get back to collecting faster.

1. the user goes forward 2 times
`A1 - A2 - A3 - A4 - U5 - U6 - U7*`
2. the user hit previous.  What feels natural:
   a. previous goes to U6 which they just saw 
   b. skips back to A4 so they can see the last plot they answered

**Comment by rjsheperd** [comment]
> src/clj/collect_earth_online/db/plots.clj
> 81-83 WRT the use cases.
 > Good question. What feels more "natural"? With:
> A1 - A2 - A3 - A4 - U5* - U6 - U7
> 
> the user hits back 4 times
> A1* - A2 - A3 - A4 - U5* - U6 - U7
> 
> The user hits next. What feels natural:
> a. next goes to A2, which they just saw
> b. skips ahead to U5 to get back to collecting faster.

Personally, it would feel quite jarring to suddenly be thrust forward to the unanalyzed plots. I think this is a question for Andrea/Karis/Valeria though.

> the user goes forward 2 times
> A1 - A2 - A3 - A4 - U5 - U6 - U7*
> 
> the user hit previous. What feels natural:
> a. previous goes to U6 which they just saw
> b. skips back to A4 so they can see the last plot they answered

Similarly, I would say it would be unusual for me to thrown back to the analyzed plots, so I would prefer A. However, this should be clarified with our UI/UX and/or PM.

**Comment by sirmspencer** [comment]
src/clj/collect_earth_online/db/plots.clj
72-84, this all reduces to
```
"natural" (concat (call-sql "select_analyzed_plots" project-id user-id false)
                  (call-sql "select_unanalyzed_plots" project-id user-id false))
``` 
on line 104
106, You dont need to resort.  The SQL queries return sorted results.

**Pull request merged**
