### PR TITLE
a single filter for both affiliations and other institutions

### PR DESCRIPTION
**Pull request by biplovbhandari**
a single filter for both affiliations and other institutions

### CODE REVIEW

**Comment by sirmspencer** [comment]
Please run eslint on this code.

**Comment by sirmspencer** [comment]
Lines 237-239, remove this header to save space
Line 241, move the create button under the institution filter
Line 343, continue this styling so that the affiliation selector is not just the size of one institution.

**Comment by biplovbhandari** [comment]
Regarding Line 237-241, I think we still need it for public users and super admin (as admin list is not shown in filtered). Instead, I have added the check to show only appropriate to save the space

I don't quite get the Line 345 styling one as this is applied to both affiliation and other institutions from Line 245 and 265.

**Comment by sirmspencer** [comment]
"your affiliations" only show 1 row.  We need to make this section bigger.
image

**Pull request merged**
