### PR TITLE
Add authentication to API routes

### PR DESCRIPTION
**Pull request by sirmspencer**
- Add API route authentication for APIs to the before method
- Move HTML route authentication to the before method
- Convert all params to queryParams (this is needed because the authentication happens before params are resolved)
- Use the same full name for queryParams (ie "projectId")
- Pull out logic from html route authentication to just return true/false
- Check for ids in the json body for post commands
- Use session for userId where userId limits query

### CODE REVIEW

**Comment by sirmspencer** [comment]
Routes that need to be authenticated:
/add-geodash-imagery (project admins only)
/geo-dash/*
/widget-layout-editor
---I was going to get with Billy after we review / merge and have him place those pages.


collection.js:
Line 154: Missing title queryParam.
geo-dash.js:
Line 43: Missing title queryParam.
widget-layout-editor.js:
Line 52: Missing title queryParam.
---Im asuming Billy left it off because its not needed here.  This looks like left over code from a different process on creating widgets.  I suggest handing this one off to Billy.  Im not a big fan of code that takes an input and gives it right back to you anyway.


geo-dash.ftl:
Lines 9-27: Why is this Javascript code in the FTL file rather than in geo-dash.js?
Line 9: let -> const
Line 10: var -> const (don't we already call this.getParameterByName("projectId") in geo-dash.js?)
Line 11: This function needs to be rewritten to use const, ?:, and not overwrite the input arguments to the function (impure).
---This is all Billys code. The vars on line 9 and 10 dont even looked used.

**Comment by lambdatronic** [comment]
- create-institution.js:
  - Line 56: intitutionId=s -> institutionId
- project-dashboard.ftl:
  - Don't pass institutionId
- review-project.js:
  - Line 250: Missing institutionId queryParam.

Regarding Billy's code, please make a Github Issue with these tasks for him so they don't get lost to history:
- Server.java:
  - Routes that need to be authenticated:
    - /add-geodash-imagery (project admins only)
    - /geo-dash/*
    - /widget-layout-editor
- collection.js:
  - Line 154: Missing title queryParam.
- geo-dash.js:
  - Line 43: Missing title queryParam.
- widget-layout-editor.js:
  - Line 52: Missing title queryParam.
- geo-dash.ftl:
  - Lines 9-27: Why is this Javascript code in the FTL file rather than in geo-dash.js?
  - Line 9: let -> const
  - Line 10: var -> const (don't we already call this.getParameterByName("projectId") in geo-dash.js?)
  - Line 11: This function needs to be rewritten to use const, ?:, and not overwrite the input arguments to the function (impure).

**Comment by lambdatronic** [comment]
- create-institution.js:
  - Line 56: intitutionId=s -> institutionId
- project-dashboard.ftl:
  - Don't pass institutionId
- review-project.js:
  - Line 250: Missing institutionId queryParam.

Regarding Billy's code, please make a Github Issue with these tasks for him so they don't get lost to history:
- Server.java:
  - Routes that need to be authenticated:
    - /add-geodash-imagery (project admins only)
    - /geo-dash/*
    - /widget-layout-editor
- collection.js:
  - Line 154: Missing title queryParam.
- geo-dash.js:
  - Line 43: Missing title queryParam.
- widget-layout-editor.js:
  - Line 52: Missing title queryParam.
- geo-dash.ftl:
  - Lines 9-27: Why is this Javascript code in the FTL file rather than in geo-dash.js?
  - Line 9: let -> const
  - Line 10: var -> const (don't we already call this.getParameterByName("projectId") in geo-dash.js?)
  - Line 11: This function needs to be rewritten to use const, ?:, and not overwrite the input arguments to the function (impure).

**Comment by sirmspencer** [comment]
review-project.js:
Line 250: Missing institutionId queryParam.
---I removed the need.  (same reason to remove it from project-dashboard.ftl)

**Pull request merged**
