### PR TITLE
CEO-458 The help title has no color if upload boundary file is selected

### PR DESCRIPTION
**Pull request by sifbiri**
## Purpose

Disable the Map Help Panel when not needed to collect input and change its colors to ligth gray to signal inactivity to users. 
## Submission Checklist
- [x] Included Jira issue in the PR title (e.g. `CEO-### <title>`)
- [x] Code passes linter rules (`npm run eslint`/`clj-kondo --lint src`)

### CODE REVIEW

**Comment by sirmspencer** [comment]
src/js/project/CreateProjectWizard.js
558, This is incorrect.  You are getting false results because isMapInactive is always undefined (the value would be this.state.isMapInactive). Just set the class to bg-lightgreen since there is no reason it should go to bg-light

**Comment by sifbiri** [comment]
isMapInactive is defined as a const in the method render. It is local variable that depends on both the state and context (current step). When the file input boundary is selected, the map is not needed and becomes disabled. I think from user perspective would be nice to signal it by changing color (gray). Just like when a button is inactive it becomes gray. 
Though maybe changing the const name to a different one, so it doesn't create confusion.

**Comment by sirmspencer** [comment]
I checked again, when you upload a file for the boundary, it shows on the map.  Im back to thinking the title doesnt need to change color (ie disabled).

image

**Comment by sirmspencer** [comment]
I am opening a new PR to make some changes.  Your code is fine, but I think we want to do this a little different.

**Pull request closed without merging**
